In [21]:
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('hr_data.csv')
#data.head()
data_select = data[['model_number', 'luminosity']]






#dataselected = data['luminosity', 'log_L']

#dataselected.plot()


#plt.show()






#headers = data.dtypes.index

       model_number  luminosity
0               610       0.916
1               611       0.916
2               612       0.916
3               613       0.915
4               614       0.915
5               615       0.915
6               616       0.915
7               617       0.915
8               618       0.915
9               619       0.914
10              620       0.914
11              621       0.913
12              622       0.913
13              623       0.912
14              624       0.912
15              625       0.911
16              626       0.910
17              627       0.909
18              628       0.907
19              629       0.906
20              630       0.904
21              631       0.902
22              632       0.900
23              633       0.897
24              634       0.895
25              635       0.892
26              636       0.889
27              637       0.887
28              638       0.884
29              639       0.882
...             ...         ...
25065         25671    5840.000
25066         25672    5840.000
25067         25673    5840.000
25068         25674    5840.000
25069         25675    5840.000
25070         25676    5840.000
25071         25677    5830.000
25072         25678    5830.000
25073         25679    5830.000
25074         25680    5830.000
25075         25681    5830.000
25076         25682    5830.000
25077         25683    5820.000
25078         25684    5820.000
25079         25685    5820.000
25080         25686    5820.000
25081         25687    5810.000
25082         25688    5810.000
25083         25689    5810.000
25084         25690    5800.000
25085         25691    5800.000
25086         25692    5790.000
25087         25693    5790.000
25088         25694    5780.000
25089         25695    5780.000
25090         25696    5770.000
25091         25697    5770.000
25092         25698    5760.000
25093         25699    5760.000
25094         25700    5750.000

[25095 rows x 2 columns]